export const SEARCH_TEAM = "SEARCH_TEAM";
export const SEARCH_TEAM_SUCCESS = "SEARCH_TEAM_SUCCESS";
export const SEARCH_TEAM_FAILED = "SEARCH_TEAM_FAILED";

export const FETCH_TEAM_LAST_FIXTURES = "FETCH_TEAM_LAST_FIXTURES";
export const FETCH_TEAM_LAST_FIXTURES_SUCCESS = "FETCH_TEAM_LAST_FIXTURES_SUCCESS";
export const FETCH_TEAM_LAST_FIXTURES_FAILED = "FETCH_TEAM_LAST_FIXTURES_FAILED";

export const FETCH_TEAM_NEXT_FIXTURES = "FETCH_TEAM_NEXT_FIXTURES";
export const FETCH_TEAM_NEXT_FIXTURES_SUCCESS = "FETCH_TEAM_NEXT_FIXTURES_SUCCESS";
export const FETCH_TEAM_NEXT_FIXTURES_FAILED = "FETCH_TEAM_NEXT_FIXTURES_FAILED";

export const CLEAR_FILTERED_TEAMS = "CLEAR_FILTERED_TEAMS";

export const FETCH_LIVE_FIXTURES = "FETCH_LIVE_FIXTURES";
export const FETCH_LIVE_FIXTURES_SUCCESS = "FETCH_LIVE_FIXTURES_SUCCESS";
export const FETCH_LIVE_FIXTURES_FAILED = "FETCH_LIVE_FIXTURES_FAILED";

export const FETCH_TEAM_LEAGUE_STANDINGS = "FETCH_TEAM_LEAGUE_STANDINGS";
export const FETCH_TEAM_LEAGUE_STANDINGS_SUCCESS = "FETCH_TEAM_LEAGUE_STANDINGS_SUCCESS";
export const FETCH_TEAM_LEAGUE_STANDINGS_FAILED = "FETCH_TEAM_LEAGUE_STANDINGS_FAILED";
